/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as CareBookingRouteImport } from './routes/care-booking'
import { Route as DesignPreviewRouteImport } from './routes/design-preview'
import { Route as HomeVisitsRouteImport } from './routes/home-visits'
import { Route as MapRouteImport } from './routes/map'
import { Route as MatchingRouteImport } from './routes/matching'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as NurseRouteImport } from './routes/nurse'
import { Route as StitchPreviewRouteImport } from './routes/stitch-preview'
import { Route as SurgeryRouteImport } from './routes/surgery'
import { Route as TechnicianRouteImport } from './routes/technician'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBookingOperationsRouteImport } from './routes/admin.booking-operations'
import { Route as AdminCredentialsRouteImport } from './routes/admin.credentials'
import { Route as AdminEmergencyRouteImport } from './routes/admin.emergency'
import { Route as AdminHomecareRouteImport } from './routes/admin.homecare'
import { Route as AdminLiveRouteImport } from './routes/admin.live'
import { Route as AdminLocumRouteImport } from './routes/admin.locum'
import { Route as AdminPhysicianRouteImport } from './routes/admin.physician'
import { Route as AdminPhysioRouteImport } from './routes/admin.physio'
import { Route as AdminTechnicianRouteImport } from './routes/admin.technician'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminWellnessRouteImport } from './routes/admin.wellness'
import { Route as DevRaceAcceptRouteImport } from './routes/dev.race-accept'
import { Route as EmergencyAmbulanceRouteImport } from './routes/emergency.ambulance'
import { Route as EmergencyDoctorRouteImport } from './routes/emergency.doctor'
import { Route as EmergencyHospitalRouteImport } from './routes/emergency.hospital'
import { Route as EmergencyPatientRouteImport } from './routes/emergency.patient'
import { Route as HospitalNurseDutiesRouteImport } from './routes/hospital.nurse-duties'
import { Route as NurseBookRouteImport } from './routes/nurse.book'
import { Route as NurseVisitsRouteImport } from './routes/nurse.visits'
import { Route as NursesFindRouteImport } from './routes/nurses.find'
import { Route as PhysioBookRouteImport } from './routes/physio.book'
import { Route as PhysioTherapistRouteImport } from './routes/physio.therapist'
import { Route as PhysioVisitsRouteImport } from './routes/physio.visits'
import { Route as ProviderAvailabilityRouteImport } from './routes/provider.availability'
import { Route as ProviderEarningsRouteImport } from './routes/provider.earnings'
import { Route as TechnicianBookRouteImport } from './routes/technician.book'
import { Route as TechnicianVisitsRouteImport } from './routes/technician.visits'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as SharedAiTokenRouteImport } from './routes/shared.ai.$token'
import { Route as ApiInternalHomeVisitsJobsRouteImport } from './routes/api/internal/home-visits/jobs'
import { Route as ApiPublicPushDispatchRouteImport } from './routes/api/public/push/dispatch'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const CareBookingRoute = CareBookingRouteImport.update({
  id: '/care-booking',
  path: '/care-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignPreviewRoute = DesignPreviewRouteImport.update({
  id: '/design-preview',
  path: '/design-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeVisitsRoute = HomeVisitsRouteImport.update({
  id: '/home-visits',
  path: '/home-visits',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchingRoute = MatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const NurseRoute = NurseRouteImport.update({
  id: '/nurse',
  path: '/nurse',
  getParentRoute: () => rootRouteImport,
} as any)
const StitchPreviewRoute = StitchPreviewRouteImport.update({
  id: '/stitch-preview',
  path: '/stitch-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const SurgeryRoute = SurgeryRouteImport.update({
  id: '/surgery',
  path: '/surgery',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianRoute = TechnicianRouteImport.update({
  id: '/technician',
  path: '/technician',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingOperationsRoute = AdminBookingOperationsRouteImport.update({
  id: '/admin/booking-operations',
  path: '/admin/booking-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCredentialsRoute = AdminCredentialsRouteImport.update({
  id: '/admin/credentials',
  path: '/admin/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmergencyRoute = AdminEmergencyRouteImport.update({
  id: '/admin/emergency',
  path: '/admin/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHomecareRoute = AdminHomecareRouteImport.update({
  id: '/admin/homecare',
  path: '/admin/homecare',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLiveRoute = AdminLiveRouteImport.update({
  id: '/admin/live',
  path: '/admin/live',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLocumRoute = AdminLocumRouteImport.update({
  id: '/admin/locum',
  path: '/admin/locum',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPhysicianRoute = AdminPhysicianRouteImport.update({
  id: '/admin/physician',
  path: '/admin/physician',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPhysioRoute = AdminPhysioRouteImport.update({
  id: '/admin/physio',
  path: '/admin/physio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTechnicianRoute = AdminTechnicianRouteImport.update({
  id: '/admin/technician',
  path: '/admin/technician',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWellnessRoute = AdminWellnessRouteImport.update({
  id: '/admin/wellness',
  path: '/admin/wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRaceAcceptRoute = DevRaceAcceptRouteImport.update({
  id: '/dev/race-accept',
  path: '/dev/race-accept',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyAmbulanceRoute = EmergencyAmbulanceRouteImport.update({
  id: '/emergency/ambulance',
  path: '/emergency/ambulance',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyDoctorRoute = EmergencyDoctorRouteImport.update({
  id: '/emergency/doctor',
  path: '/emergency/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyHospitalRoute = EmergencyHospitalRouteImport.update({
  id: '/emergency/hospital',
  path: '/emergency/hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyPatientRoute = EmergencyPatientRouteImport.update({
  id: '/emergency/patient',
  path: '/emergency/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalNurseDutiesRoute = HospitalNurseDutiesRouteImport.update({
  id: '/hospital/nurse-duties',
  path: '/hospital/nurse-duties',
  getParentRoute: () => rootRouteImport,
} as any)
const NurseBookRoute = NurseBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => NurseRoute,
} as any)
const NurseVisitsRoute = NurseVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => NurseRoute,
} as any)
const NursesFindRoute = NursesFindRouteImport.update({
  id: '/nurses/find',
  path: '/nurses/find',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysioBookRoute = PhysioBookRouteImport.update({
  id: '/physio/book',
  path: '/physio/book',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysioTherapistRoute = PhysioTherapistRouteImport.update({
  id: '/physio/therapist',
  path: '/physio/therapist',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysioVisitsRoute = PhysioVisitsRouteImport.update({
  id: '/physio/visits',
  path: '/physio/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderAvailabilityRoute = ProviderAvailabilityRouteImport.update({
  id: '/provider/availability',
  path: '/provider/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderEarningsRoute = ProviderEarningsRouteImport.update({
  id: '/provider/earnings',
  path: '/provider/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianBookRoute = TechnicianBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => TechnicianRoute,
} as any)
const TechnicianVisitsRoute = TechnicianVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => TechnicianRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const SharedAiTokenRoute = SharedAiTokenRouteImport.update({
  id: '/shared/ai/$token',
  path: '/shared/ai/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalHomeVisitsJobsRoute =
  ApiInternalHomeVisitsJobsRouteImport.update({
    id: '/api/internal/home-visits/jobs',
    path: '/api/internal/home-visits/jobs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPushDispatchRoute = ApiPublicPushDispatchRouteImport.update({
  id: '/api/public/push/dispatch',
  path: '/api/public/push/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/care-booking': typeof CareBookingRoute
  '/design-preview': typeof DesignPreviewRoute
  '/home-visits': typeof HomeVisitsRoute
  '/map': typeof MapRoute
  '/matching': typeof MatchingRoute
  '/mcp': typeof McpRoute
  '/nurse': typeof NurseRouteWithChildren
  '/stitch-preview': typeof StitchPreviewRoute
  '/surgery': typeof SurgeryRoute
  '/technician': typeof TechnicianRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/booking-operations': typeof AdminBookingOperationsRoute
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/emergency': typeof AdminEmergencyRoute
  '/admin/homecare': typeof AdminHomecareRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/locum': typeof AdminLocumRoute
  '/admin/physician': typeof AdminPhysicianRoute
  '/admin/physio': typeof AdminPhysioRoute
  '/admin/technician': typeof AdminTechnicianRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wellness': typeof AdminWellnessRoute
  '/dev/race-accept': typeof DevRaceAcceptRoute
  '/emergency/ambulance': typeof EmergencyAmbulanceRoute
  '/emergency/doctor': typeof EmergencyDoctorRoute
  '/emergency/hospital': typeof EmergencyHospitalRoute
  '/emergency/patient': typeof EmergencyPatientRoute
  '/hospital/nurse-duties': typeof HospitalNurseDutiesRoute
  '/nurse/book': typeof NurseBookRoute
  '/nurse/visits': typeof NurseVisitsRoute
  '/nurses/find': typeof NursesFindRoute
  '/physio/book': typeof PhysioBookRoute
  '/physio/therapist': typeof PhysioTherapistRoute
  '/physio/visits': typeof PhysioVisitsRoute
  '/provider/availability': typeof ProviderAvailabilityRoute
  '/provider/earnings': typeof ProviderEarningsRoute
  '/technician/book': typeof TechnicianBookRoute
  '/technician/visits': typeof TechnicianVisitsRoute
  '/admin/': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/shared/ai/$token': typeof SharedAiTokenRoute
  '/api/internal/home-visits/jobs': typeof ApiInternalHomeVisitsJobsRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/care-booking': typeof CareBookingRoute
  '/design-preview': typeof DesignPreviewRoute
  '/home-visits': typeof HomeVisitsRoute
  '/map': typeof MapRoute
  '/matching': typeof MatchingRoute
  '/mcp': typeof McpRoute
  '/nurse': typeof NurseRouteWithChildren
  '/stitch-preview': typeof StitchPreviewRoute
  '/surgery': typeof SurgeryRoute
  '/technician': typeof TechnicianRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/booking-operations': typeof AdminBookingOperationsRoute
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/emergency': typeof AdminEmergencyRoute
  '/admin/homecare': typeof AdminHomecareRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/locum': typeof AdminLocumRoute
  '/admin/physician': typeof AdminPhysicianRoute
  '/admin/physio': typeof AdminPhysioRoute
  '/admin/technician': typeof AdminTechnicianRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wellness': typeof AdminWellnessRoute
  '/dev/race-accept': typeof DevRaceAcceptRoute
  '/emergency/ambulance': typeof EmergencyAmbulanceRoute
  '/emergency/doctor': typeof EmergencyDoctorRoute
  '/emergency/hospital': typeof EmergencyHospitalRoute
  '/emergency/patient': typeof EmergencyPatientRoute
  '/hospital/nurse-duties': typeof HospitalNurseDutiesRoute
  '/nurse/book': typeof NurseBookRoute
  '/nurse/visits': typeof NurseVisitsRoute
  '/nurses/find': typeof NursesFindRoute
  '/physio/book': typeof PhysioBookRoute
  '/physio/therapist': typeof PhysioTherapistRoute
  '/physio/visits': typeof PhysioVisitsRoute
  '/provider/availability': typeof ProviderAvailabilityRoute
  '/provider/earnings': typeof ProviderEarningsRoute
  '/technician/book': typeof TechnicianBookRoute
  '/technician/visits': typeof TechnicianVisitsRoute
  '/admin': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/shared/ai/$token': typeof SharedAiTokenRoute
  '/api/internal/home-visits/jobs': typeof ApiInternalHomeVisitsJobsRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/care-booking': typeof CareBookingRoute
  '/design-preview': typeof DesignPreviewRoute
  '/home-visits': typeof HomeVisitsRoute
  '/map': typeof MapRoute
  '/matching': typeof MatchingRoute
  '/mcp': typeof McpRoute
  '/nurse': typeof NurseRouteWithChildren
  '/stitch-preview': typeof StitchPreviewRoute
  '/surgery': typeof SurgeryRoute
  '/technician': typeof TechnicianRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/booking-operations': typeof AdminBookingOperationsRoute
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/emergency': typeof AdminEmergencyRoute
  '/admin/homecare': typeof AdminHomecareRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/locum': typeof AdminLocumRoute
  '/admin/physician': typeof AdminPhysicianRoute
  '/admin/physio': typeof AdminPhysioRoute
  '/admin/technician': typeof AdminTechnicianRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wellness': typeof AdminWellnessRoute
  '/dev/race-accept': typeof DevRaceAcceptRoute
  '/emergency/ambulance': typeof EmergencyAmbulanceRoute
  '/emergency/doctor': typeof EmergencyDoctorRoute
  '/emergency/hospital': typeof EmergencyHospitalRoute
  '/emergency/patient': typeof EmergencyPatientRoute
  '/hospital/nurse-duties': typeof HospitalNurseDutiesRoute
  '/nurse/book': typeof NurseBookRoute
  '/nurse/visits': typeof NurseVisitsRoute
  '/nurses/find': typeof NursesFindRoute
  '/physio/book': typeof PhysioBookRoute
  '/physio/therapist': typeof PhysioTherapistRoute
  '/physio/visits': typeof PhysioVisitsRoute
  '/provider/availability': typeof ProviderAvailabilityRoute
  '/provider/earnings': typeof ProviderEarningsRoute
  '/technician/book': typeof TechnicianBookRoute
  '/technician/visits': typeof TechnicianVisitsRoute
  '/admin/': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/shared/ai/$token': typeof SharedAiTokenRoute
  '/api/internal/home-visits/jobs': typeof ApiInternalHomeVisitsJobsRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bookings'
    | '/care-booking'
    | '/design-preview'
    | '/home-visits'
    | '/map'
    | '/matching'
    | '/mcp'
    | '/nurse'
    | '/stitch-preview'
    | '/surgery'
    | '/technician'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/booking-operations'
    | '/admin/credentials'
    | '/admin/emergency'
    | '/admin/homecare'
    | '/admin/live'
    | '/admin/locum'
    | '/admin/physician'
    | '/admin/physio'
    | '/admin/technician'
    | '/admin/users'
    | '/admin/wellness'
    | '/dev/race-accept'
    | '/emergency/ambulance'
    | '/emergency/doctor'
    | '/emergency/hospital'
    | '/emergency/patient'
    | '/hospital/nurse-duties'
    | '/nurse/book'
    | '/nurse/visits'
    | '/nurses/find'
    | '/physio/book'
    | '/physio/therapist'
    | '/physio/visits'
    | '/provider/availability'
    | '/provider/earnings'
    | '/technician/book'
    | '/technician/visits'
    | '/admin/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/shared/ai/$token'
    | '/api/internal/home-visits/jobs'
    | '/api/public/push/dispatch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bookings'
    | '/care-booking'
    | '/design-preview'
    | '/home-visits'
    | '/map'
    | '/matching'
    | '/mcp'
    | '/nurse'
    | '/stitch-preview'
    | '/surgery'
    | '/technician'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/booking-operations'
    | '/admin/credentials'
    | '/admin/emergency'
    | '/admin/homecare'
    | '/admin/live'
    | '/admin/locum'
    | '/admin/physician'
    | '/admin/physio'
    | '/admin/technician'
    | '/admin/users'
    | '/admin/wellness'
    | '/dev/race-accept'
    | '/emergency/ambulance'
    | '/emergency/doctor'
    | '/emergency/hospital'
    | '/emergency/patient'
    | '/hospital/nurse-duties'
    | '/nurse/book'
    | '/nurse/visits'
    | '/nurses/find'
    | '/physio/book'
    | '/physio/therapist'
    | '/physio/visits'
    | '/provider/availability'
    | '/provider/earnings'
    | '/technician/book'
    | '/technician/visits'
    | '/admin'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/shared/ai/$token'
    | '/api/internal/home-visits/jobs'
    | '/api/public/push/dispatch'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bookings'
    | '/care-booking'
    | '/design-preview'
    | '/home-visits'
    | '/map'
    | '/matching'
    | '/mcp'
    | '/nurse'
    | '/stitch-preview'
    | '/surgery'
    | '/technician'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/booking-operations'
    | '/admin/credentials'
    | '/admin/emergency'
    | '/admin/homecare'
    | '/admin/live'
    | '/admin/locum'
    | '/admin/physician'
    | '/admin/physio'
    | '/admin/technician'
    | '/admin/users'
    | '/admin/wellness'
    | '/dev/race-accept'
    | '/emergency/ambulance'
    | '/emergency/doctor'
    | '/emergency/hospital'
    | '/emergency/patient'
    | '/hospital/nurse-duties'
    | '/nurse/book'
    | '/nurse/visits'
    | '/nurses/find'
    | '/physio/book'
    | '/physio/therapist'
    | '/physio/visits'
    | '/provider/availability'
    | '/provider/earnings'
    | '/technician/book'
    | '/technician/visits'
    | '/admin/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/shared/ai/$token'
    | '/api/internal/home-visits/jobs'
    | '/api/public/push/dispatch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BookingsRoute: typeof BookingsRoute
  CareBookingRoute: typeof CareBookingRoute
  DesignPreviewRoute: typeof DesignPreviewRoute
  HomeVisitsRoute: typeof HomeVisitsRoute
  MapRoute: typeof MapRoute
  MatchingRoute: typeof MatchingRoute
  McpRoute: typeof McpRoute
  NurseRoute: typeof NurseRouteWithChildren
  StitchPreviewRoute: typeof StitchPreviewRoute
  SurgeryRoute: typeof SurgeryRoute
  TechnicianRoute: typeof TechnicianRouteWithChildren
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminBookingOperationsRoute: typeof AdminBookingOperationsRoute
  AdminCredentialsRoute: typeof AdminCredentialsRoute
  AdminEmergencyRoute: typeof AdminEmergencyRoute
  AdminHomecareRoute: typeof AdminHomecareRoute
  AdminLiveRoute: typeof AdminLiveRoute
  AdminLocumRoute: typeof AdminLocumRoute
  AdminPhysicianRoute: typeof AdminPhysicianRoute
  AdminPhysioRoute: typeof AdminPhysioRoute
  AdminTechnicianRoute: typeof AdminTechnicianRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWellnessRoute: typeof AdminWellnessRoute
  DevRaceAcceptRoute: typeof DevRaceAcceptRoute
  EmergencyAmbulanceRoute: typeof EmergencyAmbulanceRoute
  EmergencyDoctorRoute: typeof EmergencyDoctorRoute
  EmergencyHospitalRoute: typeof EmergencyHospitalRoute
  EmergencyPatientRoute: typeof EmergencyPatientRoute
  HospitalNurseDutiesRoute: typeof HospitalNurseDutiesRoute
  NursesFindRoute: typeof NursesFindRoute
  PhysioBookRoute: typeof PhysioBookRoute
  PhysioTherapistRoute: typeof PhysioTherapistRoute
  PhysioVisitsRoute: typeof PhysioVisitsRoute
  ProviderAvailabilityRoute: typeof ProviderAvailabilityRoute
  ProviderEarningsRoute: typeof ProviderEarningsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  SharedAiTokenRoute: typeof SharedAiTokenRoute
  ApiInternalHomeVisitsJobsRoute: typeof ApiInternalHomeVisitsJobsRoute
  ApiPublicPushDispatchRoute: typeof ApiPublicPushDispatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-booking': {
      id: '/care-booking'
      path: '/care-booking'
      fullPath: '/care-booking'
      preLoaderRoute: typeof CareBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-preview': {
      id: '/design-preview'
      path: '/design-preview'
      fullPath: '/design-preview'
      preLoaderRoute: typeof DesignPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-visits': {
      id: '/home-visits'
      path: '/home-visits'
      fullPath: '/home-visits'
      preLoaderRoute: typeof HomeVisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matching': {
      id: '/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof MatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nurse': {
      id: '/nurse'
      path: '/nurse'
      fullPath: '/nurse'
      preLoaderRoute: typeof NurseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stitch-preview': {
      id: '/stitch-preview'
      path: '/stitch-preview'
      fullPath: '/stitch-preview'
      preLoaderRoute: typeof StitchPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surgery': {
      id: '/surgery'
      path: '/surgery'
      fullPath: '/surgery'
      preLoaderRoute: typeof SurgeryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician': {
      id: '/technician'
      path: '/technician'
      fullPath: '/technician'
      preLoaderRoute: typeof TechnicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/booking-operations': {
      id: '/admin/booking-operations'
      path: '/admin/booking-operations'
      fullPath: '/admin/booking-operations'
      preLoaderRoute: typeof AdminBookingOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/credentials': {
      id: '/admin/credentials'
      path: '/admin/credentials'
      fullPath: '/admin/credentials'
      preLoaderRoute: typeof AdminCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/emergency': {
      id: '/admin/emergency'
      path: '/admin/emergency'
      fullPath: '/admin/emergency'
      preLoaderRoute: typeof AdminEmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/homecare': {
      id: '/admin/homecare'
      path: '/admin/homecare'
      fullPath: '/admin/homecare'
      preLoaderRoute: typeof AdminHomecareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/live': {
      id: '/admin/live'
      path: '/admin/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AdminLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/locum': {
      id: '/admin/locum'
      path: '/admin/locum'
      fullPath: '/admin/locum'
      preLoaderRoute: typeof AdminLocumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/physician': {
      id: '/admin/physician'
      path: '/admin/physician'
      fullPath: '/admin/physician'
      preLoaderRoute: typeof AdminPhysicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/physio': {
      id: '/admin/physio'
      path: '/admin/physio'
      fullPath: '/admin/physio'
      preLoaderRoute: typeof AdminPhysioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/technician': {
      id: '/admin/technician'
      path: '/admin/technician'
      fullPath: '/admin/technician'
      preLoaderRoute: typeof AdminTechnicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wellness': {
      id: '/admin/wellness'
      path: '/admin/wellness'
      fullPath: '/admin/wellness'
      preLoaderRoute: typeof AdminWellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/race-accept': {
      id: '/dev/race-accept'
      path: '/dev/race-accept'
      fullPath: '/dev/race-accept'
      preLoaderRoute: typeof DevRaceAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency/ambulance': {
      id: '/emergency/ambulance'
      path: '/emergency/ambulance'
      fullPath: '/emergency/ambulance'
      preLoaderRoute: typeof EmergencyAmbulanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency/doctor': {
      id: '/emergency/doctor'
      path: '/emergency/doctor'
      fullPath: '/emergency/doctor'
      preLoaderRoute: typeof EmergencyDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency/hospital': {
      id: '/emergency/hospital'
      path: '/emergency/hospital'
      fullPath: '/emergency/hospital'
      preLoaderRoute: typeof EmergencyHospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency/patient': {
      id: '/emergency/patient'
      path: '/emergency/patient'
      fullPath: '/emergency/patient'
      preLoaderRoute: typeof EmergencyPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/nurse-duties': {
      id: '/hospital/nurse-duties'
      path: '/hospital/nurse-duties'
      fullPath: '/hospital/nurse-duties'
      preLoaderRoute: typeof HospitalNurseDutiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nurse/book': {
      id: '/nurse/book'
      path: '/book'
      fullPath: '/nurse/book'
      preLoaderRoute: typeof NurseBookRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurse/visits': {
      id: '/nurse/visits'
      path: '/visits'
      fullPath: '/nurse/visits'
      preLoaderRoute: typeof NurseVisitsRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurses/find': {
      id: '/nurses/find'
      path: '/nurses/find'
      fullPath: '/nurses/find'
      preLoaderRoute: typeof NursesFindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physio/book': {
      id: '/physio/book'
      path: '/physio/book'
      fullPath: '/physio/book'
      preLoaderRoute: typeof PhysioBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physio/therapist': {
      id: '/physio/therapist'
      path: '/physio/therapist'
      fullPath: '/physio/therapist'
      preLoaderRoute: typeof PhysioTherapistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physio/visits': {
      id: '/physio/visits'
      path: '/physio/visits'
      fullPath: '/physio/visits'
      preLoaderRoute: typeof PhysioVisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/availability': {
      id: '/provider/availability'
      path: '/provider/availability'
      fullPath: '/provider/availability'
      preLoaderRoute: typeof ProviderAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/earnings': {
      id: '/provider/earnings'
      path: '/provider/earnings'
      fullPath: '/provider/earnings'
      preLoaderRoute: typeof ProviderEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/book': {
      id: '/technician/book'
      path: '/book'
      fullPath: '/technician/book'
      preLoaderRoute: typeof TechnicianBookRouteImport
      parentRoute: typeof TechnicianRoute
    }
    '/technician/visits': {
      id: '/technician/visits'
      path: '/visits'
      fullPath: '/technician/visits'
      preLoaderRoute: typeof TechnicianVisitsRouteImport
      parentRoute: typeof TechnicianRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/ai/$token': {
      id: '/shared/ai/$token'
      path: '/shared/ai/$token'
      fullPath: '/shared/ai/$token'
      preLoaderRoute: typeof SharedAiTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/home-visits/jobs': {
      id: '/api/internal/home-visits/jobs'
      path: '/api/internal/home-visits/jobs'
      fullPath: '/api/internal/home-visits/jobs'
      preLoaderRoute: typeof ApiInternalHomeVisitsJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/dispatch': {
      id: '/api/public/push/dispatch'
      path: '/api/public/push/dispatch'
      fullPath: '/api/public/push/dispatch'
      preLoaderRoute: typeof ApiPublicPushDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NurseRouteChildren {
  NurseBookRoute: typeof NurseBookRoute
  NurseVisitsRoute: typeof NurseVisitsRoute
}

const NurseRouteChildren: NurseRouteChildren = {
  NurseBookRoute: NurseBookRoute,
  NurseVisitsRoute: NurseVisitsRoute,
}

const NurseRouteWithChildren = NurseRoute._addFileChildren(NurseRouteChildren)

interface TechnicianRouteChildren {
  TechnicianBookRoute: typeof TechnicianBookRoute
  TechnicianVisitsRoute: typeof TechnicianVisitsRoute
}

const TechnicianRouteChildren: TechnicianRouteChildren = {
  TechnicianBookRoute: TechnicianBookRoute,
  TechnicianVisitsRoute: TechnicianVisitsRoute,
}

const TechnicianRouteWithChildren = TechnicianRoute._addFileChildren(
  TechnicianRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BookingsRoute: BookingsRoute,
  CareBookingRoute: CareBookingRoute,
  DesignPreviewRoute: DesignPreviewRoute,
  HomeVisitsRoute: HomeVisitsRoute,
  MapRoute: MapRoute,
  MatchingRoute: MatchingRoute,
  McpRoute: McpRoute,
  NurseRoute: NurseRouteWithChildren,
  StitchPreviewRoute: StitchPreviewRoute,
  SurgeryRoute: SurgeryRoute,
  TechnicianRoute: TechnicianRouteWithChildren,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminBookingOperationsRoute: AdminBookingOperationsRoute,
  AdminCredentialsRoute: AdminCredentialsRoute,
  AdminEmergencyRoute: AdminEmergencyRoute,
  AdminHomecareRoute: AdminHomecareRoute,
  AdminLiveRoute: AdminLiveRoute,
  AdminLocumRoute: AdminLocumRoute,
  AdminPhysicianRoute: AdminPhysicianRoute,
  AdminPhysioRoute: AdminPhysioRoute,
  AdminTechnicianRoute: AdminTechnicianRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWellnessRoute: AdminWellnessRoute,
  DevRaceAcceptRoute: DevRaceAcceptRoute,
  EmergencyAmbulanceRoute: EmergencyAmbulanceRoute,
  EmergencyDoctorRoute: EmergencyDoctorRoute,
  EmergencyHospitalRoute: EmergencyHospitalRoute,
  EmergencyPatientRoute: EmergencyPatientRoute,
  HospitalNurseDutiesRoute: HospitalNurseDutiesRoute,
  NursesFindRoute: NursesFindRoute,
  PhysioBookRoute: PhysioBookRoute,
  PhysioTherapistRoute: PhysioTherapistRoute,
  PhysioVisitsRoute: PhysioVisitsRoute,
  ProviderAvailabilityRoute: ProviderAvailabilityRoute,
  ProviderEarningsRoute: ProviderEarningsRoute,
  AdminIndexRoute: AdminIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  SharedAiTokenRoute: SharedAiTokenRoute,
  ApiInternalHomeVisitsJobsRoute: ApiInternalHomeVisitsJobsRoute,
  ApiPublicPushDispatchRoute: ApiPublicPushDispatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
